name: Update Clinician Summary

on:
  push:
    paths:
      - 'ALL-HOURS.csv'
    branches:
      - main
      - 'claude/**'

permissions:
  contents: write

jobs:
  regenerate-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run backend.py to regenerate clinician_summary.csv
        run: |
          python backend.py
          mkdir -p public
          cp clinician_summary.csv public/

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet clinician_summary.csv public/clinician_summary.csv; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add clinician_summary.csv public/clinician_summary.csv
          git commit -m "Auto-update clinician_summary.csv from ALL-HOURS.csv changes"
          git push
